### ISSUE TITLE
Using Json file with complex json

### ISSUE THREAD

**Issue by Sandeep321** [hishamco/My.Extensions.Localization.Json#1]
I trued using the package and it works fine with simpple json like : {
  "Hello": "Bonjour"
}
But it did not work with complex json like 
{
  "Hello": {
    "Key": "Hello"
     }
  }

I tried using localizer["Hello.Key"] to access the value Hello.

Is it possible with this package, if yes how.

Or else can you please add that functionality as well.

**Comment by Sandeep321** [comment]
It works by using localizer["Hello:Text"]. So closing it. 👍

**Comment by hishamco** [comment]
Yep, because `:` is the  delimiter that have been used in the configuration. Happy to hear that's working
