### ISSUE TITLE
How will it handle the localization of model Validations

### ISSUE THREAD

**Issue by Sandeep321** [hishamco/My.Extensions.Localization.Json#2]
I wanted DataAnnotations Like [Required], [Display], [Range] to be localized. I tried some ways as I found over StackOverflow etc but nothing seems right for this Json localizer.

Any idea on how to accomplish the same. Sample code would be really helpfull.

**Comment by hishamco** [comment]
Before I dig into, please check the [LocalizationSample.Web](https://github.com/aspnet/Entropy/tree/master/samples/Localization.StarterWeb), because my `JsonLocalizer` should work as same as `StringLocalizer` except it looks for the resources from the JSON files

> I tried some ways as I found over StackOverflow etc but nothing seems right for this Json localizer

Can you point to some of those?

**Comment by Sandeep321** [comment]
Got it working after trying out a couple of approaches. I got it working it using just couple of lines as 
`            services.AddMvc()
                 .AddDataAnnotationsLocalization(o =>
                 {
                     var factory = services.BuildServiceProvider().GetService<IStringLocalizerFactory>();
                     var localizer = factory.Create(typeof(Resource));
                     o.DataAnnotationLocalizerProvider = (t, f) => localizer;
                 })
                 .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);`

Where Resource is your Resource Class name which matches with the json file name.

Now my model looks like:
`
public class LocalizationModel
    {
        [Required(ErrorMessage = "The {0} field is required.")]
        [MaxLength(4, ErrorMessage = "The field {0} must be a string or array type with a maximum length of '{1}'.")]
        public string Name { get; set; }

        [Range(0, 10, ErrorMessage = "The field {0} must be between {1} and {2}.")]
        public int Id { get; set; } 
    }
`

My Resource.en.json file looks like:
`{
  "The {0} field is required.": "The {0} field is required.",
  "The field {0} must be a string or array type with a maximum length of '{1}'.": "The field {0} must be a string or array type with a maximum length of '{1}'.",
  "The field {0} must be between {1} and {2}.": "The field {0} must be between {1} and {2}."
}`

You can use some more readable keys in json file and then do rest of the changes as required

**Comment by hishamco** [comment]
Hope you share your repo if it's public, so I can create a link for it

**Comment by Sandeep321** [comment]
I will create one and share soon. and provide the link here.

**Comment by hishamco** [comment]
Thanks .. I appreciated!!

**Comment by Sandeep321** [comment]
@hishamco I have created one example with localization working with DataAnnotations also. 
https://github.com/Sandeep321/asp.netcore-JsonResourceLocalizer
might be helpful

**Comment by hishamco** [comment]
As I see the DataAnnotations issue that you talked about before isn't related directly to the `JsonLocalizer` perhaps a setup issue, furthermore I expect that you 'll reference my package that's published in NuGet rather than copy paste the code again without adding a value 😄

**Comment by abarrak** [comment]
Thank you @Sandeep321 for sharing.
This addresses an issue we had with `DataAnnotation`, and confirmed a solution we expected to work.

[CC: @Muhammad-Altabba].

**Comment by abarrak** [comment]
I wonder @hishamco though if it's possible to add this setup it into the library.
For example, using extension method to MVC, e.g. Add**JSON**DataAnnotationsLocalization() maybe?

**Comment by hishamco** [comment]
@abarrak the DataAnnotation stuff is handled in the MVC. I will open a new issue with your suggestion and investigate on that

**Comment by feliperesendebr** [comment]
I tried every way I thought possible and I never managed to make the location work in the Required, Display and Length attributes.

I don't know if I did it wrong or if it's not compatible.

I'm testing .NET Core 8 Blazor Server.

Could anyone help me please?

**Comment by hishamco** [comment]
@feliperesendebr could you please file a new issue with a reproduced steps so I can test too
