### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by khaledobaid** [hishamco/My.Extensions.Localization.Json#22]
FileLoadException: The given assembly name or codebase was invalid. (0x80131047)

in StringLocalizer.cs 
_localizer = factory.Create(string.Empty, PathHelpers.GetApplicationRoot());

**Comment by hishamco** [comment]
Hi @khaledobaid

Sorry for delay due the Internet cable issue in our country, regarding to the reported bug is it occur on the code base or in your project that reference the json localized?

**Comment by hishamco** [comment]
Fixed in 4f13064a42390c3e14861249c1082772d38f494d
