### ISSUE TITLE
Localization in startup project doesn't work.

### ISSUE THREAD

**Issue by TPIvan** [hishamco/My.Extensions.Localization.Json#23]
Parameter type and json file name in `LocalizationSample` are inconsistent.
There is
 
     public void Configure(IApplicationBuilder app, IHostingEnvironment env, IStringLocalizer<Model> localizer)

in  `Startup` class. However the the file name is `Startup.fr-FR.json`. 

Either the file name should be `Model.fr-FR.json` or the parameter should be `IStringLocalizer<Startup>`.

**Comment by hishamco** [comment]
Thanks for reporting this, let me check or submit a PR if you interest

**Comment by TPIvan** [comment]
I have a copy opened in VS connected to TFS (not git) so PR is a bit difficult for me.

**Comment by hishamco** [comment]
No problem I will have a look to it now

**Comment by hishamco** [comment]
@TPIvan the file named `Model.fr-FR.json`, I don't see an issue with that, could you rebase to the latest bits?

**Comment by TPIvan** [comment]
I mean the file [`Startup.fr-FR.json`](https://github.com/hishamco/My.Extensions.Localization.Json/blob/master/samples/LocalizationSample/Resources/Startup.fr-FR.json) in [LocalizationSample/Resources](https://github.com/hishamco/My.Extensions.Localization.Json/tree/master/samples/LocalizationSample/Resources). I think that the name should be (as you have said) `Model.fr-FR.json`.

**Comment by hishamco** [comment]
I meant the `Model.fr-FR.json` which located in `LocalizationSample.Resources`

Let me do a quick run without changing anything

**Comment by TPIvan** [comment]
It seems like each of us sees a different file. Please check the [image ](https://imgur.com/a/v19vdid).

**Comment by hishamco** [comment]
Fixed in a672ac1588db4be70a06342e43f5e49ed1734588, I'm sure I pass a `Model` for a reason, I revise the old commits

Thanks
