### ISSUE TITLE
[Question] When will the latest version be available as a NuGet package?

### ISSUE THREAD

**Issue by thomkle** [hishamco/My.Extensions.Localization.Json#24]
Hi,

As mentioned in the title, I'm wondering when the latest version that was just pushed will be available as a NuGet package (https://www.nuget.org/packages/My.Extensions.Localization.Json). It doesn't seem to have been updated for a while.

**Comment by hishamco** [comment]
You 're right, I tried yesterday to push them into GitHub Packages first, seems I will push them directly on NuGet

Thanks

**Comment by hishamco** [comment]
I will review the code today to check if there's a breaking changes from the 1st version

**Comment by hishamco** [comment]
Please check this https://www.nuget.org/packages/My.Extensions.Localization.Json/2.0.0

**Comment by thomkle** [comment]
@hishamco Thanks a lot for a quick response and push!

Works very well.

**Comment by hishamco** [comment]
Thanks for pushing me at this time ;)

**Comment by thomkle** [comment]
@hishamco Another question, any plans to support fallback-functionality? E.g. say I have a TestController and the files testcontroller.es-ES.json, testcontroller.es.json and testcontroller.json. The fallback-functionality would first check the testcontroller.es-ES.json for the key, then the testcontroller.es.json and then testcontroller.json.

**Comment by hishamco** [comment]
Could you please move it into a new issue?

**Comment by thomkle** [comment]
Of course!
