### ISSUE TITLE
Not working in a multi project setup

### ISSUE THREAD

**Issue by dradovic** [hishamco/My.Extensions.Localization.Json#3]
Hey, thanks for the short and sweet library. Unfortunately, I doesn't work in a multi-project scenario because the base directory is always the one that is currently executing (probably the web project) and then resources are referenced relative to that.
But what I want to support is for example:

    MyCompany.Core
        Resources
            SomeCoreSpecificResources.de-CH.json
    MyCompany.Web
        Resources
             SomeWebSpecificResources.de-CH.json

So the JSON needs to be found in a different project. My idea is to embed the JSON into the assembly so that path manipulations and such become obsolete. I'll probably fork from your project to give it a try.

**Comment by hishamco** [comment]
You can have a try, and I will have look to make use of `ResourceLocationAttribute` if it's needed
thanks

**Comment by hishamco** [comment]
Embed json files should work with you, but I'm asking in case if you have multi projects, the resources should be placed in the host, because its the only project that you need to deploy with other projects binaries

**Comment by hishamco** [comment]
@dradovic I come up with two ways:
1-Embedding the json files, which is the thing that I don't prefer, but we can find a way to discover the localization resources
2- If the is a modular structure, there should be entry point for each module, there's where the module can register the resources location

**Comment by hishamco** [comment]
Fixed in commit https://github.com/hishamco/My.Extensions.Localization.Json/commit/2bc6ce14daa88c31bae517a73c406c9fcf5505dd and there's a show case added in the samples folder
