### ISSUE TITLE
Use single localization file for all cultures

### ISSUE THREAD

**Issue by hishamco** [hishamco/My.Extensions.Localization.Json#31]
I'm not sure if it's useful to have a single file that contains all the localization strings for the supported cultures

```json
{
  "Hello": 
  {
      "en": "Hello",
      "fr": "Bonjour"
  }
}
```

**Comment by kylehu16** [comment]
it's useful.Because mostly we will load this file once,not every times

**Comment by hishamco** [comment]
You are right, but it will load unnecessary localized strings also unnecessary cultures if you are using one or two

I may consider this or feel free to submit a PR

**Comment by hishamco** [comment]
Having a single file is too much and will lose a lot of advantages such as caching, so using single file per culture - which is currently supported - is a better option
