### ISSUE TITLE
Support AddJsonDataAnnotationsLocalization()

### ISSUE THREAD

**Issue by hishamco** [hishamco/My.Extensions.Localization.Json#5]
Based on the comment https://github.com/hishamco/My.Extensions.Localization.Json/issues/2#issuecomment-515098347

**Comment by hishamco** [comment]
Seems doable, I'm glad if you want to send a PR for it, otherwise I 'll do it myself :)

**Comment by Muhammad-Altabba** [comment]
I created a pull request for this. Kindly review and issue a new NuGet package.
Many thanks,

---
Thanks to @abarrak,

**Comment by hishamco** [comment]
Thanks for your PR, please have a look to my comments there ..
