### ISSUE TITLE
assign culture in runtime

### ISSUE THREAD

**Issue by vovanb** [hishamco/My.Extensions.Localization.Json#53]
I want to configure culture in appsettings.json. If exist a way to assign culture in runtime?
I tried in startup.cs put below 
```
            const string culture = "fr-FR";
            CultureInfo ci = CultureInfo.GetCultureInfo(culture);

            Thread.CurrentThread.CurrentCulture = ci;
            Thread.CurrentThread.CurrentUICulture = ci;
```

But it did not help....

**Comment by hishamco** [comment]
> I want to configure culture in appsettings.json

Seems you are talking about `JsonResquestCultureProvider` which I blogged about years ago, that code you wrote above should sets the culture, could you tell me where you wrote it?

Please let me what your intend, so I can answer properly

**Comment by vovanb** [comment]
yes this is what I asked:
http://www.hishambinateya.com/localization-and-configuration-in-asp.net-core-2.0-part-1-json-request-culture-provider

I missed  DefaultRequestCulture = new RequestCulture("en-US"),
Thank you

**Comment by hishamco** [comment]
All the best
