### ISSUE TITLE
Have one resource file for project

### ISSUE THREAD

**Issue by vovanb** [hishamco/My.Extensions.Localization.Json#54]
Is it possible to have one resource file for all project without creating Views->Home  or controllers,Views.Home.Privacy

**Comment by hishamco** [comment]
I think you mean `SharedResource`?

**Comment by vovanb** [comment]
the idea is to put all translations in one single json file and use it from all pages

**Comment by hishamco** [comment]
Yah!! that's what I meant before, hope to create a sample for that if it's not exist

**Comment by hishamco** [comment]
If you wanna to try it, it's my pleasure to accept your PR

**Comment by vovanb** [comment]
I would be happy to make changes, but can you please point where from to start?

**Comment by hishamco** [comment]
@vovanb after revising the code, what you asking for is already implemented, please have a look to `LocalizationSample`, there's a `fr-FR.json` which contains a shared resources that can be accessible through `IStringLocalizer`

**Comment by vovanb** [comment]
not sure I fallow you. I see exist two resources fr-FR.json and Startup.fr-FR.json. I want to use in all MVC pages ( Layout,Index) singe file. So what step I need to perform?

**Comment by hishamco** [comment]
1. Create a json file per culture

2. Add all of your localization resources

3. Access them using `IStringLocalizer`

That is it!!

**Comment by vovanb** [comment]
I tried in index.cshtml to use 
@inject IStringLocalizer Localizer instead of 
@inject IViewLocalizer Localizer 
but got not found exception ... and once I added reference to @using Microsoft.Extensions.Localization; I got can not load exception

**Comment by hishamco** [comment]
No no .. you can replace `IViewLocalizer` with `IStringLocalizer`, instead use it in your controller or page model

Let me have a look ...

**Comment by hishamco** [comment]
@vovanb any updates?

**Comment by hishamco** [comment]
I will close this one while there's no update from the author
