### ISSUE TITLE
Any plan to switch the project to a .NET standard class library ?

### ISSUE THREAD

**Issue by fededim** [hishamco/My.Extensions.Localization.Json#55]
In this way your package could also be used in WebAssembly Blazor applications.

**Comment by hishamco** [comment]
I was thinking about Blazor while it's beta, perhaps I need to revise this soon while the localisation are supported now

Thanks

**Comment by hishamco** [comment]
If you want to pick this one I will be glad, we need a sample too to ensure nothing breaks

**Comment by hishamco** [comment]
I did some progress on this one, seems we need to remove the `IHostingEnvironment` dependency, coz it's not registered by default in Blazor

**Comment by fededim** [comment]
Ok, the problem I see is that there is no hosting environment in blazor client side, that's why it has been removed...just to understand why do you need it ? You need to access contentrootpath or webrootpath ?

**Comment by hishamco** [comment]
>  I see is that there is no hosting environment in blazor client side,

Nope, there's `IWebAssemblyHostEnvironment` that can be accessed via `WebAssemblyHostBuilder`

> Do you need to access contentrootpath or webrootpath ?

https://github.com/hishamco/My.Extensions.Localization.Json/blob/3b2c4c657caaabb799549060497dd830aea2f11a/src/My.Extensions.Localization.Json/Internal/StringLocalizer.cs#L12

Yep, but seems it's save to remove it now - for the upcoming major release - while it's not used

**Comment by hishamco** [comment]
Still there's another exception I got, I'm working to fix it ...

**Comment by hishamco** [comment]
Here is #56 a WIP, you can have a try to fix the current bug if you are interested

**Comment by fededim** [comment]
Which bug are you talking about ?

**Comment by hishamco** [comment]
I'm not sure, but while I'm injecting `IStringLocalizer` I got some exception in the console, probably something goes wrong

**Comment by hishamco** [comment]
FYI: `netstandard` now has been supported in PR #56, there's a known issue in Blazor WebAssembly only
