### ISSUE TITLE
How to use with DataAnnotation?

### ISSUE THREAD

**Issue by HamedFathi** [hishamco/My.Extensions.Localization.Json#57]
Is it possible to use it with `DataAnnotation`? Any sample?

**Comment by hishamco** [comment]
Of course it's possible, I remembered this had been triggered by @Muhammad-Altabba long time ago in #9, you could have a look to #2 for more information

Please let me know if you face any issue, it should work as it works in `ResourceManager`

**Comment by HamedFathi** [comment]
Honestly, I tried but failed and built a repository. Can anyone help me?

[JsonResource](https://github.com/HamedFathi/JsonResource)

**Comment by hishamco** [comment]
Ok, no worry I will have a look or provide a sample in the repo soon

**Comment by hishamco** [comment]
I think it will not make difference either Web API, MVC or Razor Pages

**Comment by hishamco** [comment]
@HamedFathi you could try my PR #59, I added a data annotation support to the MVC sample it should work with other applications type too

**Comment by HamedFathi** [comment]
@hishamco 

Thank you so much, Although I tried to simulate your approach in my [JsonResource](https://github.com/HamedFathi/JsonResource) sample it failed!

I still do not understand what I have set wrong.
Anyway, thank you.

**Comment by hishamco** [comment]
Is your sample using the `JsonStringLocalizer` or your own localizer?

**Comment by HamedFathi** [comment]
@hishamco 

`IStringLocalizer<>` [here](https://github.com/HamedFathi/JsonResource/blob/b19495906db3bac175955e0940be0e9d20bf0fd0/JsonResource/Controllers/WeatherForecastController.cs#L24)

**Comment by hishamco** [comment]
I mean you didn't use JSON?

**Comment by hishamco** [comment]
The line you point to will localize the strings that will be used by the controller not the data annotations

**Comment by HamedFathi** [comment]
![image](https://user-images.githubusercontent.com/8418700/95051701-881b1900-06fa-11eb-9c3b-8db6472b5543.png)

**Comment by hishamco** [comment]
At the first glance no need to provide a full path for the resources folder, just make it "Resources" if it not working I will check your repo on my laptop and see what's going on

**Comment by HamedFathi** [comment]
I had checked your tip before. Does not work. 

No pressure, It would be great if you have time to check my repository. Definitely I make a mistake.

Thanks in advance.

**Comment by hishamco** [comment]
My tip is necessary before you go further, I will have a look once I have a time

**Comment by hishamco** [comment]
It works with me with two changes ;)

```csharp
services.AddJsonLocalization(opt => opt.ResourcesPath = "Resources");

services.AddControllers()
    .AddDataAnnotationsLocalization(options =>
    {
        options.DataAnnotationLocalizerProvider = (type, factory) =>
            factory.Create(typeof(Validation));
    });
```

**Comment by HamedFathi** [comment]
@hishamco  I did not know their order is important!

Thank you so much

**Comment by hishamco** [comment]
Localization should come first, so anything after should be aware of the localization APIs, hope the sample is working with you
