### ISSUE TITLE
LocalizationSample project is not working

### ISSUE THREAD

**Issue by neman** [hishamco/My.Extensions.Localization.Json#61]
When I `dotnet run` LocalizationSample I get the following errror:

> Application startup exception: System.Exception: Could not resolve a service of type 'Microsoft.Extensions.Localization.IStringLocalizer' for the parameter 'localizer1' of method 'Configure' on type 'LocalizationSample.Startup'.
>  ---> System.IO.FileLoadException: The given assembly name or codebase was invalid. (0x80131047)
>    at System.Reflection.AssemblyName.nInit()
>    at System.Reflection.AssemblyName..ctor(String assemblyName)
>    at My.Extensions.Localization.Json.JsonStringLocalizerFactory.<>c__DisplayClass7_0.<Create>b__0(String _) in C:\Users\nemke\Documents\GitHub\My.Extensions.Localization.Json\src\My.Extensions.Localization.Json\JsonStringLocalizerFactory.cs:line 81

When I remove `IStringLocalizer localizer1` from injecting into ctor of  **Configure** method, the sample runs ok.

**Comment by hishamco** [comment]
Thanks @neman for reporting this, which dotnet version your are using?

**Comment by hishamco** [comment]
I can reproduce the issue, I will figure out why this happen ..

**Comment by hishamco** [comment]
Fixed in https://github.com/hishamco/My.Extensions.Localization.Json/commit/78bf2723697a9629ecac65115c90d83238145283
