### ISSUE TITLE
About NET5.0 Blazor WebAssembly Uses My.Extensions.Localization.Json

### ISSUE THREAD

**Issue by GreenShadeZhang** [hishamco/My.Extensions.Localization.Json#62]
A limited set of ASP.NET Core's localization scenarios are currently supported:

IStringLocalizer and IStringLocalizer<T> are supported in Blazor apps.
IHtmlLocalizer, IViewLocalizer, and Data Annotations localization are ASP.NET Core MVC scenarios and not supported in Blazor apps.

When I use it, there's a Microsoft.AspNetCore.Mvc.Localization reference, so can this library separate the code so that NET5.0 Blazor WebAssembly works.

Also, can the name of this library be changed to a more formal name? The name gives a less formal feel.

**Comment by hishamco** [comment]
Hi @GreenShadeZhang I did some localization in Oqtane Framework (Blazor), I may look again into the `JsonLocalizer`

> Also, can the name of this library be changed to a more formal name? The name gives a less formal feel.

I'm not sure if it's the right time, I followed the same naming convension of ASP.NET Core Extensions at the beginning, I think it's not a big issue while there's a tags attached on the NuGet package

Thanks

**Comment by GreenShadeZhang** [comment]
Sorry, I just care about this word my, the others are very good, thank you for your help in troubleshooting net5.0 blazor webassembly, thank you very much.

**Comment by GreenShadeZhang** [comment]
> Hi @GreenShadeZhang I did some localization in Oqtane Framework (Blazor), I may look again into the `JsonLocalizer`
> 
> > Also, can the name of this library be changed to a more formal name? The name gives a less formal feel.
> 
> I'm not sure if it's the right time, I followed the same naming convension of ASP.NET Core Extensions at the beginning, I think it's not a big issue while there's a tags attached on the NuGet package
> 
> Thanks

Hello, have you tested some problems in the NET5.0 Blazor WebAssembly project?

**Comment by hishamco** [comment]
Sorry @GreenShadeZhang I was busy last few days, hope to do it today or tommrow, could you please create a minimal repo, so I can easily figure out the issue and test it

**Comment by GreenShadeZhang** [comment]
> Sorry @GreenShadeZhang I was busy last few days, hope to do it today or tommrow, could you please create a minimal repo, so I can easily figure out the issue and test it

https://github.com/GreenShadeZhang/BlazorAppTest 

This is a NET5.0 Blazor WebAssembly test project, the main reason is to expose Microsoft.AspNetCore.Mvc namespace problems, I looked at the source code NET5.0 Blazor WebAssembly multi-language only used Microsoft.Extensions.Localization, your library is implemented razor page and mvc interface, I hope you'll help you see if you're going to leave the library alone for Blackzor Web Assembly or continue in compatibility mode.

**Comment by hishamco** [comment]
Thanks @GreenShadeZhang, I will have a look ...

**Comment by hishamco** [comment]
Seems I was wrong when I add `Microsoft.AspNetCore.Mvc.Localization` I will try to look to the commits history

**Comment by hishamco** [comment]
I figure out the issue, which came from introduing `JsonHtmlLocalizer`, so I will move into into another assembly, so Blazor will not complain then ...

**Comment by hishamco** [comment]
PR #46 is the main reason for this, a better solution is to create another package for MVC specific localization

**Comment by hishamco** [comment]
@GreenShadeZhang I just removed the dependency, hopefully I will release the upcoming release with few days, you could try GitHub Packages for now without waiting https://github.com/hishamco?tab=packages&repo_name=My.Extensions.Localization.Json please let me know if this fix your issue

**Comment by GreenShadeZhang** [comment]
> @GreenShadeZhang I just removed the dependency, hopefully I will release the upcoming release with few days, you could try GitHub Packages for now without waiting https://github.com/hishamco?tab=packages&repo_name=My.Extensions.Localization.Json please let me know if this fix your issue

When I use the package you remove, there will also be an error, as if it were an error caused by a resource path read, and it is recommended that you test it with the NET5.0 Blazor WebAssembly project.

![image](https://user-images.githubusercontent.com/24240675/105192155-cb4aac00-5b72-11eb-9cc1-11675f0cf9de.png)

**Comment by hishamco** [comment]
Please refer me to the page that causes the issue, I will try to update the blazor sample to `NET5.0`

**Comment by GreenShadeZhang** [comment]
> Please refer me to the page that causes the issue, I will try to update the blazor sample to `NET5.0`

Hello this time I test your code, I upgraded sdk to net5.0, managed in server mode, running your code is normal, but when I use WebAssembly to produce file read problems, the cause of the problem is that the json file read place blazor has adjustments, resulting in not being able to take the path to get jason files, this is my guess, I hope you have time also test, originally I intended to give a pr but I did not test successfully.

**Comment by hishamco** [comment]
Feel free to submit a PR if it's required, I will check the Blazor WebAssembly app too

**Comment by hishamco** [comment]
We update to .NET 7 reopen if you still facing the issue
