### ISSUE TITLE
Class based localisation only works when the class is in the root namespace

### ISSUE THREAD

**Issue by chrispaynter** [hishamco/My.Extensions.Localization.Json#66]
I have a basic structure like this

```
/MyProject.csproj
/Resources/Problems.cs
/Resources/Problems.en-GB.json
```

If I try to use `IStringLocalizer<Problems>` with this configuration, my localisation strings don't work.

However, if I change my file structure to this
```
/MyProject.csproj
/Problems.cs
/Resources/Problems.en-GB.json
```

Then the strings now work.

It seems that we can only use classes so long as they exist in the root namespace. You can't place the class anywhere else.

Would be preferable if we can put the marker classes in the same folder as the resources.

**Comment by chrispaynter** [comment]
My workaround at the moment is to have the files in the resources folder, but make sure the namespace of the marker class is the root namespace of the project.

**Comment by hishamco** [comment]
Hi @chrispaynter, you need to set the resources folder with

```csharp
services.AddJsonLocalization(options => options.ResourcesPath = "Resources");
```

In your case you have to set it that to `String.Empty`, have a try or let me know if it doesn't work

**Comment by chrispaynter** [comment]
Hi @hishamco , thanks for the response. I've actually already done this.

I'll try and get you a minimal repo, under the pump at the minute.

**Comment by chrispaynter** [comment]
Hi @hishamco thanks for the reply.

Wouldn't that mean then that all my resources have to be in the root of the project, rather than in the `Resources` folder? (which is where I want them to be).

**Comment by hishamco** [comment]
You should specify the resources path, so that's why I told you to set it to `String.Empty` instead of specifying a resources folder

**Comment by hishamco** [comment]
I will close while there's no reply from the author
