### ISSUE TITLE
Support for hierarchical keys?

### ISSUE THREAD

**Issue by stepanStanc** [hishamco/My.Extensions.Localization.Json#76]
In version 3.0.1 it was possible to use hierarchical keys (:) thanks to the configurations API that is used https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#configuration-keys-and-values.  After this issue https://github.com/hishamco/My.Extensions.Localization.Json/issues/29 and this change https://github.com/hishamco/My.Extensions.Localization.Json/commit/ecf716931fb46384a59319e9502479a21001922e that stopped being supported in version 3.1.0. 

Would it be possible to bring support for this back, or should an alternate approach be taken?

**Comment by hishamco** [comment]
We could think about an alternative solution for this. Feel free to open a PR if you want

**Comment by hishamco** [comment]
> What was the motivation for using System.Text.Json instead?

This was the plan, there're new APIs that make parsing JSON much easier and more efficient

**Comment by hishamco** [comment]
Sorry @stepanStanc for this taking so long, please remind me is the hierarchical keys used colon in the past, I need to bring this feature back if it's necessary or think about alternative way

**Comment by hishamco** [comment]
Hierarchical keys are back 🚀, please let me know if you have any feedback
