### ISSUE TITLE
ResourcesPath Issue with IIS vistual directory

### ISSUE THREAD

**Issue by redabakr** [hishamco/My.Extensions.Localization.Json#8]
![Screenshot_072819_115525_AM](https://user-images.githubusercontent.com/4567122/62005109-9650cb00-b12e-11e9-95cf-d7be7ffff968.jpg)

Everything is working fine locally, but on the server, it can't find the json files

**Comment by hishamco** [comment]
I'm wondering there are two folders instead of one that represents the app

**Comment by hishamco** [comment]
@redabakr could you please try your project again with latest bits aka nightly builds?

**Comment by hishamco** [comment]
I will close this for now, feel free to re open it if the issue still exist
