### ISSUE TITLE
how can refresh cache?

### ISSUE THREAD

**Issue by ByZhouhang** [hishamco/My.Extensions.Localization.Json#82]
in my project  i use this project  and IStringLocalizer

When I change the internationalization prompt,  i will mofiy json file immediately   and want the program to return the modified prompt immediately， but I find that the program returns the same prompt as before 

`
return ResponseOutput.NotOk(_localizer["TrialMaint_PersonnelJoined"]);

`

**Comment by hishamco** [comment]
To clarify, are you asking that you localize a resource and then change the `json` file so it doesn't reflect?

**Comment by ByZhouhang** [comment]
> To clarify, are you asking that you localize a resource and then change the `json` file so it doesn't reflect?

yes，When I debugged the breakpoint, I confirmed that the json file was indeed modified, but the values I saw in IStringLocalizer were still the same as before

**Comment by hishamco** [comment]
You need to restart the app. I remember in the past I used the Configuration system so it reloads the data automatically when the source is changed

Please let me check and get back to you

**Comment by hishamco** [comment]
@ByZhouhang do you want to submit a PR to refresh the cache when the underlying storage changes?

**Comment by ByZhouhang** [comment]
> @ByZhouhang do you want to submit a PR to refresh the cache when the underlying storage changes?@ByZhouhang 

I've never submitted a PR, maybe it's better if you have time to fix this

**Comment by hishamco** [comment]
I struggled for to last few days to add a few features, I just released `3.3.0` version, hope to spend some time to fix this issue
